# -*- coding: utf-8 -*-
"""3진수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WB5wwFwD71Shi5Kd876NxNnStqgAyQmi
"""

l=[]
while n>0:
    l.append(n%3)
    n//=3
answer=0
for i in range(len(l)):
    answer+=l[i]*(3**(len(l)-i-1))
answer

