# -*- coding: utf-8 -*-
"""JadenCase 문자열 만들기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(s):
    answer = ''
    s=s.lower()
    l=list(s.split(' '))
    l2=[]
    for i in l:
        l2.append(list(i))
    for i in l2:
        if i!=[]:
          i[0]=i[0].upper()
    for i in l2:
        if i==[]:
          answer+=' '
        for j in i:
            if j==i[0]:
                answer+=' '
            answer+=j
            
    return answer[1:]