# -*- coding: utf-8 -*-
"""K번째수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(array, commands):
    answer = []
    for i,j,k in commands:
       try: 
        answer.append(sorted(array[i-1:j])[k-1])
       except: 
        answer.append(sorted(array[i-1:])[k-1])
    return answer