# -*- coding: utf-8 -*-
"""x만큼 간격이 있는 n개의 숫자.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(x, n):
    l=[]
    a=x
    for i in range(n):
        l.append(a)
        a+=x
    return l