# -*- coding: utf-8 -*-
"""가운데 글자 가져오기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(s):
    if len(s)%2!=0:    
        answer = s[len(s)//2]
    else:
        answer=s[(len(s)//2-1):len(s)//2+1]
    return answer