# -*- coding: utf-8 -*-
"""나누어 떨어지는 숫자 배열

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qHBKtDUgZpyBVGyhZQZDo1UBg3MfWC8X
"""

def solution(arr, divisor):
    answer = []
    for i in arr:
        if i%divisor==0:
            answer.append(i)
    if len(answer)==0:
        answer.append(-1)
    return sorted(answer)