# -*- coding: utf-8 -*-
"""나머지가 1이 되는 수 찾기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KdAmXJto7SHorOtiXExR4tzlzlXqbQuC
"""

def solution(n):
    for i in range(2,n):
        if n%i==1:
            return i
            break
    return