# -*- coding: utf-8 -*-
"""내적.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(a, b):
    answer=0
    for i in range(len(a)):
        answer+=a[i]*b[i]
    
    return answer