# -*- coding: utf-8 -*-
"""다음 큰 숫자.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def number_of_one(n):
    num = 0
    while n>0:
        if n%2==1:
            num+=1
        n//=2
    return num
    

def solution(n):
    answer = n+1
    while number_of_one(n)!=number_of_one(answer):
        answer+=1
    return answer