# -*- coding: utf-8 -*-
"""단어정렬.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WB5wwFwD71Shi5Kd876NxNnStqgAyQmi
"""

N=int(input())
words=[]
for _ in range(N):
    words.append(input())
words.sort()
words2=dict()
for word in words:
  words2[word]=len(word)
words2=sorted(words2.items(),key=lambda x:x[1])
for i,j in words2:
  print(i)