# -*- coding: utf-8 -*-
"""두 개 뽑아서 더하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(numbers):
    temp=numbers
    answer = []
    for i in temp.sort():
        temp.remove(i)
        #print(i)
        for j in temp.sort():
            answer.append(i+j)
            #print(temp)
    answer=sorted(list(set(answer)))
    #print(answer)
    return answer