# -*- coding: utf-8 -*-
"""땅따먹기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

#https://shanepark.tistory.com/183

def solution(land):
    answer = 0
    for i in range(len(land)-1):
        land[i+1][0]+=max(land[i][1],land[i][2],land[i][3])
        land[i+1][1]+=max(land[i][0],land[i][2],land[i][3])
        land[i+1][2]+=max(land[i][1],land[i][0],land[i][3])
        land[i+1][3]+=max(land[i][1],land[i][2],land[i][0])
    print(max(land[len(land)-1]))
    # [실행] 버튼을 누르면 출력 값을 볼 수 있습니다.

    return max(land[len(land)-1])