# -*- coding: utf-8 -*-
"""문자열 내 마음대로 정렬하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qHBKtDUgZpyBVGyhZQZDo1UBg3MfWC8X
"""

def solution(strings, n):
    dic={}
    for i in sorted(strings):
        dic[i]=i[n]
    answer=sorted(dic, key=lambda x: dic[x])
    return answer