# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KdAmXJto7SHorOtiXExR4tzlzlXqbQuC
"""

def solution(price, money, count):
    answer=((count*(count+1)*price)/2)-money
    if answer<0:
        answer=0
    return answer