# -*- coding: utf-8 -*-
"""소수 만들기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(nums):
    l=[]
    for i in nums:
        for j in nums:
            for k in nums:
                if i<j and j<k:
                    l.append(i+j+k)
    # 에라토스테네스의 체
    erat=[True]*3000
    for i in range(2,int(3000**0.5)):
      j=i
      if erat[i]:
        while i*j<3000:
          erat[i*j]=False
          j+=1
    # answer 세기
    answer=0
    for i in l:
      if erat[i]:
        answer+=1
    return answer