# -*- coding: utf-8 -*-
"""수 정렬하기3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WB5wwFwD71Shi5Kd876NxNnStqgAyQmi
"""

# import sys
# input = sys.stdin.readline
# print = sys.stdout.write

l=[0]*10000
num=int(input())
for i in range(num):
  n=int(input())
  l[n-1]+=1
for i in range(1,10001):
  for j in range(l[i-1]):
    print(i)