# -*- coding: utf-8 -*-
"""숫자 문자열과 영단어.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WB5wwFwD71Shi5Kd876NxNnStqgAyQmi
"""

# 1: list
N=int(input())
members=[]
for _ in range(N):
    members.append(input())

one=sorted(one,key=lambda x:x[0])
two=sorted(two,key=lambda x:x[:2])
three=sorted(three,key=lambda x:x[:3])
if len(one)>0:
  print(*one,sep='\n')
if len(two)>0:
  print(*two,sep='\n')
if len(three)>0:
  print(*three,sep='\n')

# 21 Ju, 3 Do, 100 Su, 89 Me, 21 Hy, 1 Do

# 21 Ju, 1 Do, 100 Su, 89 Me, 21 Hy, 3 Do

# 2: dict

N=int(input())
members={}
for i in range(N):
    age,name=input().split()
    members[age.ljust(8+len(str(age))-len(str(i)),'*')+str(i)]=name
print(members)
for i in sorted(members,key=lambda x:int(x[:-8])):
    print(i[:-8], members[i])