# -*- coding: utf-8 -*-
"""신규 아이디 추천.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(new_id):
    
    string=['-','_','.']
    # 1단계: 소문자
    new_id=new_id.lower()
    # 2단계: 특수문자 제거
    for i in new_id:
        if i not in [chr(j) for j in range(ord('a'),ord('z')+1)]+[str(j) for j in range(10)]+string:
            new_id=new_id.replace(i,'')
    # 3단계: ..->.
    while '..' in new_id:
        new_id=new_id.replace('..','.')     
    # 4단계: 처음이나 끝 . 제거
    if new_id[0]=='.':
        new_id=new_id[1:]
    if len(new_id)>0 and new_id[-1]=='.':
            new_id=new_id[:-1]
    # 5단계: 빈 문자열 'a'
    if len(new_id)==0:
        new_id='a'
    # 6단계: 15자
    if len(new_id)>=16:
        new_id=new_id[:15]
        if new_id[-1]=='.':
            new_id=new_id[:-1]
    #7단계: 3자
    if len(new_id)<=2:
        while len(new_id)!=3:
            new_id+=new_id[-1]
    return new_id