# -*- coding: utf-8 -*-
"""실패율.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WB5wwFwD71Shi5Kd876NxNnStqgAyQmi
"""

def solution(N, stages):
    answer = []
    failed=dict()
    for i in range(1,N+1):
        trys=0
        for j in range(len(stages)):
            if i<=stages[j]:
                trys+=1
        if trys>0:
          failed[i]=stages.count(i)/trys
        else:
          failed[i]=0
    for i in sorted(failed.items(), key=lambda x:x[1],reverse=True):
        answer.append(i[0])
    return answer