# -*- coding: utf-8 -*-
"""약수의 개수와 덧셈.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WB5wwFwD71Shi5Kd876NxNnStqgAyQmi
"""

answer = 0
for i in range(left,right+1):
    if int(i**0.5)==i**0.5:
        answer-=i
    else:
        answer+=i