# -*- coding: utf-8 -*-
"""없는 숫자 더하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(numbers):
    answer = 45-sum(numbers)
    return answer