# -*- coding: utf-8 -*-
"""예산.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(d, budget):
    answer = 0
    d=sorted(d)
    for i in d:
        if budget>=i:
            budget-=i
            answer+=1
            
    return answer