# -*- coding: utf-8 -*-
"""완주하지 못한 선수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WB5wwFwD71Shi5Kd876NxNnStqgAyQmi
"""

def solution(participant, completion):
    if len(list(set(participant)))==len(list(set(completion)))+1:
        return list(set(participant)-set(completion))[0]
    else:
        for i in completion:
            if participant.count(i)!=completion.count(i):
                return i