# -*- coding: utf-8 -*-
"""직사각형 별찍기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

a, b = map(int, input().strip().split(' '))

for i in range(b):
    print('*'*a,end='\n')