# -*- coding: utf-8 -*-
"""체육복.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WB5wwFwD71Shi5Kd876NxNnStqgAyQmi
"""

def solution(n, lost, reserve):
    for i in list(set(lost) & set(reserve)):
      reserve.remove(i)
      lost.remove(i)
    answer = n-len(lost)
    lost.sort()
    reserve.sort()
    while len(lost)*len(reserve)>0:
      if abs(lost[0]-reserve[0])==1:
          lost.remove(lost[0])
          reserve.remove(reserve[0])
          answer+=1

      elif lost[0]<reserve[0]:
          lost.remove(lost[0])
      elif lost[0]>reserve[0]:
        reserve.remove(reserve[0])
    return answer