# -*- coding: utf-8 -*-
"""최댓값과 최솟값.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(s):
    l=list(map(int,s.split()))
    return str(min(l))+' '+str(max(l))