# -*- coding: utf-8 -*-
"""최솟값 만들기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(A,B):
    answer = 0
    A.sort()
    B.sort(reverse=True)
    for i in range(len(A)):
        print(A[i]*B[i])
        answer+=A[i]*B[i]
    # [실행] 버튼을 누르면 출력 값을 볼 수 있습니다.

    return answer