# -*- coding: utf-8 -*-
"""크레인 인형뽑기 게임.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(board, moves):    
    answer = 0
    moves.append(-1)
    basket=[]
    for i in range(len(moves)):
        j=0
        while j<max(moves):
            if board[j][moves[i]-1]!=0:
                basket.append(board[j][moves[i]-1])
                board[j][moves[i]-1]=0
                break
            else:
                j+=1
    i=0    
    answer=0
    while i<len(basket)-1:
        if basket[i]==basket[i+1]:
            basket.pop(i)
            basket.pop(i)
            i=0
            answer+=2
        else:
            i+=1

    print(basket)

    return answer