# -*- coding: utf-8 -*-
"""키패드 누르기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WB5wwFwD71Shi5Kd876NxNnStqgAyQmi
"""

def solution(numbers, hand):
    answer = ''
    now_left=10
    now_right=12    
    for i in numbers:
        if i==0:
            i=11
        if i%3==1 or now_left==i:
            now_left=i
            answer+='L'
        elif i%3==0 or now_right==i:
            now_right=i
            answer+='R'

        else:
            is_right=abs(now_right-i)
            is_left=abs(now_left-i)
            how_far={1:1,3:1,2:2,4:2,6:2,5:3,7:3,9:3,8:4,10:4}
            if how_far[is_right]>how_far[is_left]:
                answer+='L'
                now_left=i
            elif how_far[is_right]<how_far[is_left]:
                answer+='R'
                now_right=i
            elif hand=='right':
                answer+='R'
                now_right=i
            else:
                answer+='L'
                now_left=i                            
    return answer