# -*- coding: utf-8 -*-
"""폰켓몬.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WB5wwFwD71Shi5Kd876NxNnStqgAyQmi
"""

def solution(nums):
    answer = 0
    pkm=len(set(nums))
    if pkm>=len(nums)//2:
        answer=len(nums)//2
    else:
        answer=pkm
    return answer