# -*- coding: utf-8 -*-
"""피보나치 수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(n):
    answer = 0
    fbnc=[0,1]
    for i in range(n):
        answer=sum(fbnc)
        fbnc.remove(fbnc[0])
        fbnc.append(answer)
    return fbnc[0]%1234567

# 참고
# def fibonacci(num):
#     a,b = 0,1
#     for i in range(num):
#         a,b = b,a+b
#     return a