# -*- coding: utf-8 -*-
"""행렬의 곱셈.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

def solution(arr1, arr2):
    real_ans=[]
    for i in range(len(arr1)):
        answer = []
        for k in range(len(arr2[0])):
            num=0
            for j in range(len(arr1[0])):
                num+=arr1[i][j]*arr2[j][k]
            answer.append(num)
        real_ans.append(answer)
    return real_ans