# -*- coding: utf-8 -*-
"""괄호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

N=int(input())
for _ in range(N):
  yn=[]
  sentence=input()
  for i in sentence:
      if i=='(':
        yn.append(i) 
      elif i==')':
        if len(yn)>0 and yn[-1]=='(':
          yn.pop()
        else:
          yn.append(i)
          break
  if len(yn)>0:
    print('NO')
  else:
    print('YES')