# -*- coding: utf-8 -*-
"""나이순 정렬.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

import sys
N=int(sys.stdin.readline())
members={}
for i in range(N):
    age,name=sys.stdin.readline().split()
    members[age.ljust(8+len(str(age))-len(str(i)),'*')+str(i)]=name
for i in sorted(members,key=lambda x:int(x[:-8])):
    print(i[:-8], members[i])