# -*- coding: utf-8 -*-
"""덩치.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

N=int(input())

ent=[]
for _ in range(N):
  a=list(map(int,input().split()))
  ent.append(a)

for i in range(N):
  n=0
  for j in range(N):
    if ent[i][0]<ent[j][0] and ent[i][1]<ent[j][1]:
      n+=1
  print(n+1,end=' ')