# -*- coding: utf-8 -*-
"""덱.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

import sys
from collections import deque
N=int(sys.stdin.readline())
deq=deque()
for _ in range(N):
    cmd=sys.stdin.readline().rstrip()
    try:
        if cmd=='pop_front':
            print(deq.popleft())
        elif cmd=='pop_back':
            print(deq.pop())
        elif cmd=='size':
            print(len(deq))
        elif cmd=='front':
            print(deq[0])
        elif cmd=='back':
            print(deq[-1])
        elif 'push_back' in cmd:
            deq.append(cmd[10:]) 
        elif 'push_front' in cmd:
            deq.appendleft(cmd[11:])
        elif len(deq)==0:
            print(1)
        else:
            print(0)
    except:
        print(-1)