# -*- coding: utf-8 -*-
"""설탕배달.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

n=int(input())
if n in[4,7]:
    print(-1)
else:
 answer=n//5
 k=0
 while n>=0:
    if (n-(5*answer))%5==0:
        answer+=(n-(5*answer))//5
        break
    else:
        n-=3
        k+=1
 print(answer+k)