# -*- coding: utf-8 -*-
"""소수 찾기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

N=int(input())
listN=list(map(int,input().split()))
N=1000
answer=0
erat=[False]+[True]*(999)
for i in range(2,int(N**0.5)+1):
  for j in range(i,N):
    try:
      erat[i*j-1]=False
    except:
      pass
for i in listN:
  if erat[i-1]:
    answer+=1
print(answer)