# -*- coding: utf-8 -*-
"""소수 구하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

M,N=map(int,input().split())
# 에라토스테네스의 체
eratos=[False,False]+[True]*N
for i in range(2,int(N**0.5)+1):
    j=i
    if eratos[i]:
        while i*j<=N:
            eratos[i*j]=False
            j+=1
for i in range(M,N+1):
    if eratos[i]:
        print(i)