# -*- coding: utf-8 -*-
"""수 정렬하기2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

import sys
N=int(sys.stdin.readline())
result=[int(sys.stdin.readline()) for _ in range(N)]
result.sort()
print(*result,sep='\n')