# -*- coding: utf-8 -*-
"""수 찾기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

N=int(input())
A_list=list(map(int,input().split()))
M=int(input())
A_list.sort()
Question=list(map(int,input().split()))

for i in Question:
  start=0
  end=N-1
  mid=(end+start)//2
  while True:
    if i in [A_list[start],A_list[mid],A_list[end]]:
      print(1)
      break  
    elif mid in [start,end]:
      print(0)
      break        
    if i<A_list[mid]:
      end=mid
    else:
      start=mid
    mid=(end+start)//2