# -*- coding: utf-8 -*-
"""숫자카드2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

import sys
N=int(sys.stdin.readline())
cards=sys.stdin.readline().split()
dic_cards={}
for i in range(N):
  dic_cards[cards[i]]=0
for i in range(N):
  if cards[i] in dic_cards.keys():
    dic_cards[cards[i]]+=1
M=sys.stdin.readline()
sanggeun=sys.stdin.readline().split()

for i in sanggeun:
  if i in dic_cards.keys():
    print(dic_cards[i],end=' ')
  else:
    print(0,end=' ')