# -*- coding: utf-8 -*-
"""스택.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

import sys
l=[]
for _ in range(int(sys.stdin.readline())):
    command=sys.stdin.readline().rstrip()
    try:
        if command=='top':
            print(l[-1])
        elif command=='pop':
            print(l.pop())
        elif command=='size':
            print(len(l))
        elif command[:4]=='push':
            l.append(command[5:])
        elif len(l)==0:
            print(1)
        else:
            print(0)
    except:
        print(-1)