# -*- coding: utf-8 -*-
"""영화감독 숌.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

n = int(input())

x = 0
y = 0

while y!=n:
    x+=1
    str_x = str(x)
    if '666' in str_x:
        y += 1

print(str_x)