# -*- coding: utf-8 -*-
"""제로.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

K=int(input())
n=[0]
for _ in range(K):
    t=int(input())
    if t!=0:
        n[0]+=t
        n.append(t)
    else:
        n[0]-=n[-1]
        n.pop()
print(n[0])