# -*- coding: utf-8 -*-
"""좌표 정렬하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

import sys

ls=[list(map(int,sys.stdin.readline().split())) for _ in range(int(sys.stdin.readline()))]
for i,j in sorted(ls,key=lambda x:(x[1],x[0])):
  print(i,j)