# -*- coding: utf-8 -*-
"""큐.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

import sys
N=int(sys.stdin.readline())
q=[]
for _ in range(N):
    cmd=sys.stdin.readline().rstrip()
    try:
        if cmd=='pop':
            print(q.pop(0))
        elif cmd=='size':
            print(len(q))
        elif cmd=='front':
            print(q[0])
        elif cmd=='back':
            print(q[-1])
        elif cmd[0]=='p':
            q.append(cmd[5:])
        elif len(q)==0:
            print(1)
        else:
            print(0)
    except:
        print(-1)