# -*- coding: utf-8 -*-
"""프린터 큐.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQjQYSkEdUCPFeqeUPdPsDXcMPPH6WUM
"""

N=int(input())
for _ in range(N):
    num,paper=map(int,input().split())
    point=list(map(int,input().split()))
    l=[]
    for i in range(num):
        point[i]+=10**(-num//10)*i
        mine=point[paper]
    l2=point
    while [int(i) for i in point]!=sorted([int(i) for i in point],reverse=True):
        if int(point[0])!=int(max(point)):
          point.append(point.pop(0))
        else:
          l.append(point[0])
          point.pop(0)
        l2=l+point
    print(l2.index(mine)+1)